In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
df = pd.read_csv("nlpp.csv")
print(df)

               word  pos
0                 ఆ  DEM
1            తరువాత  NST
2       హైదరాబాదుకు  NNP
3             బదిలీ   NN
4           అయ్యాడు   VM
...             ...  ...
9061       చెరువులు   NN
9062          ఉండటం   VM
9063       విశేషంగా   RB
9064  చెప్పుకోవచ్చు   VM
9065           </s>  END

[9066 rows x 2 columns]


In [21]:
df=df[df['pos']!='START']
df=df[df['pos']!='END']

In [23]:
import numpy as np

tags = np.unique(df['pos'])
def funTwo(word):
  c=np.where(tags==word)
  return c[0][0]
df['index_pos']=df['pos'].apply(funTwo)

In [24]:
df.head()

word  pos  index_pos
0            ఆ  DEM          2
1       తరువాత  NST          7
2  హైదరాబాదుకు  NNP          6
3        బదిలీ   NN          5
4      అయ్యాడు   VM         18

In [25]:
voc=np.unique(df['word'])
voc[:10]
voc_size=len(voc)
voc_size

2267

In [26]:
tags
tags2id={i:w for i,w in enumerate(tags)}
tags2id

{0: 'CC',
 1: 'CL',
 2: 'DEM',
 3: 'INTF',
 4: 'JJ',
 5: 'NN',
 6: 'NNP',
 7: 'NST',
 8: 'PRP',
 9: 'PSP',
 10: 'QC',
 11: 'QF',
 12: 'QO',
 13: 'RB',
 14: 'RDP',
 15: 'RP',
 16: 'SYM',
 17: 'UT',
 18: 'VM',
 19: 'WQ'}

In [27]:
sen=[]
tot_sen=[]
pos=[]
tot_pos=[]
ind=[]
tot_ind=[]

c=-1
for i in df.index:
  if c+1==i:
    sen.append(df['word'][i])
    pos.append(df['pos'][i])
    ind.append(df['index_pos'][i])
    c=i
  else:
    tot_sen.append(sen)
    tot_pos.append(pos)
    tot_ind.append(ind)
    pos=[]
    sen=[]
    ind=[]
    c=i

In [28]:
update_df = pd.DataFrame({'sen':tot_sen,'pos':tot_pos,'index_pos':tot_ind})
update_df.head()

sen  \
0           [ఆ, తరువాత, హైదరాబాదుకు, బదిలీ, అయ్యాడు]   
1        [గ్రామంలో, ప్రజల, ప్రధాన, వృత్తి, వ్యవసాయం]   
2  [ఆంధ్ర, ప్రదేశ్, రాష్ట్రములోని, రంగారెడ్డి, జి...   
3          [పురస్కారం, గ్రహీత, విశ్వనాథ, సత్యనారాయణ]   
4  [గ్రామము, కోస్గి, నుంచి, మద్దూరు, వెళ్ళు, మార్...   

                                  pos                  index_pos  
0             [DEM, NST, NNP, NN, VM]           [2, 7, 6, 5, 18]  
1                [NN, NN, JJ, NN, NN]            [5, 5, 4, 5, 5]  
2  [NNP, NN, NN, NNP, NN, VM, JJ, NN]  [6, 5, 5, 6, 5, 18, 4, 5]  
3                    [NN, NN, NN, NN]               [5, 5, 5, 5]  
4      [NN, VM, PSP, NNP, NN, NN, VM]    [5, 18, 9, 6, 5, 5, 18]

In [29]:
corpus=[]
def dead(sen):
    sent=' '.join([str(elem) for elem in sen])
    corpus.append(sent)
    return sent
update_df['sent']=update_df['sen'].apply(dead)

In [30]:
corpus

['ఆ తరువాత హైదరాబాదుకు బదిలీ అయ్యాడు',
 'గ్రామంలో ప్రజల ప్రధాన వృత్తి వ్యవసాయం',
 'ఆంధ్ర ప్రదేశ్ రాష్ట్రములోని రంగారెడ్డి జిల్లాకు చెందిన ఒక మండలము',
 'పురస్కారం గ్రహీత విశ్వనాథ సత్యనారాయణ',
 'గ్రామము కోస్గి నుంచి మద్దూరు వెళ్ళు మార్గములో కలదు',
 'కేవలం ఐదవ తరగతి వరకు మాత్రమే పాఠశాల సౌకర్యం ఉంది',
 'సభ్యులు రవిచంద్ర మరియు కాసుబాబు మరియు వికీపీడియా అజ్ఞాత సభ్యులు కృతిపై ఆధారితం',
 'రవాణా వ్యవస్థ పరిమాణం క్రమంలో దేశాల జాబితా ఇక్కడ ఇవ్వబడింది',
 'సంఘం ఒక కులాల కూటమి',
 'ఏదో ఒక పేజీకి లింకు పెట్టండి',
 'ముఖ్యమైన గ్రామాలలో ఇది ఒకటి',
 'చుట్టు ప్రక్కల పది గ్రామాలకు నీటి సరఫరా జరుగుతున్నది',
 'వ్యాసం సృష్టి మరియు లేదా విస్తరణ',
 'ఢిల్లీ బెంగళూరు హైదరాబాదు నేరుగా విమాన సేవలు ఉన్నాయి',
 'వికీపీడియా : తొలగింపు వ్యాసాలు పేజీలో జరిగే చర్చ',
 'ఛాలా ఆనందం గా వుంది',
 'బొమ్మలు ఎలా అప్లోడు చెయ్యాలి',
 'వాడే విధానం పేజీలను ఒక సారి చదవండి',
 'ఊరు విజయవాడ చాలా దగ్గర',
 'ప్రస్తుతం పాత మస్కట్ లేదా పాత నగరం అని కూడా అంటారు',
 'జిల్లా ఆంధ్రప్రదేశ్ జిల్లా',
 'వాడే బొమ్మలకు ప్రత్యేకంగా ఓ లైసెన్సు పద్ధతి ఉండొచ్

In [31]:
update_df['sent'].to_csv('data.txt', index=False, sep='\t')

In [32]:
update_df['index_pos']=tot_ind
# type(update_df['index_pos'][0][0])

In [18]:
pip install tensorflow

^C
Note: you may need to restart the kernel to use updated packages.


In [20]:
import tensorflow as tf
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.layers import Dense, LSTM, Input, Dropout,Embedding,TimeDistributed, Bidirectional
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import one_hot

In [33]:
word2id = {w: i for i, w in enumerate(df['word'])}
word2id

{'ఆ': 6866,
 'తరువాత': 5667,
 'హైదరాబాదుకు': 4890,
 'బదిలీ': 3,
 'అయ్యాడు': 4,
 'ఈ': 7065,
 'గ్రామంలో': 6555,
 'ప్రజల': 7,
 'ప్రధాన': 6708,
 'వృత్తి': 6649,
 'వ్యవసాయం': 6498,
 'కుత్బుల్లాపూర్ై\x80\x8c': 2555,
 'ఆంధ్ర': 7057,
 'ప్రదేశ్': 7058,
 'రాష్ట్రములోని': 7059,
 'రంగారెడ్డి': 6976,
 'జిల్లాకు': 7061,
 'చెందిన': 7062,
 'ఒక': 7063,
 'మండలము': 7064,
 'జ్ఞానపీఠ': 3642,
 'పురస్కారం': 21,
 'గ్రహీత': 5183,
 'విశ్వనాథ': 3317,
 'సత్యనారాయణ': 6395,
 'గ్రామము': 6768,
 'కోస్గి': 3109,
 'నుంచి': 28,
 'మద్దూరు': 29,
 'వెళ్ళు': 6964,
 'మార్గములో': 6968,
 'కలదు': 6925,
 'ఇక్కడ': 6921,
 'కేవలం': 3237,
 'ఐదవ': 1428,
 'తరగతి': 6208,
 'వరకు': 4195,
 'మాత్రమే': 3847,
 'పాఠశాల': 6092,
 'సౌకర్యం': 6924,
 'ఉంది': 7029,
 'వికీపీడియా': 6996,
 'సభ్యులు': 3730,
 'రవిచంద్ర': 3274,
 'మరియు': 7045,
 'కాసుబాబు': 5572,
 'అజ్ఞాత': 3729,
 'కృతిపై': 3731,
 'ఆధారితం': 3732,
 'రైలు': 7031,
 'రవాణా': 7036,
 'వ్యవస్థ': 1606,
 'పరిమాణం': 664,
 'క్రమంలో': 851,
 'దేశాల': 666,
 'జాబితా': 6871,
 'ఇవ్వబడింది': 61,
 'హిందూ': 

In [34]:

onehot_rep=[one_hot(words,voc_size)for words in corpus]
onehot_rep

[[862, 1374, 100, 1436, 140],
 [757, 1026, 443, 717, 2046],
 [1414, 1048, 1158, 1493, 1397, 2225, 2207, 1341],
 [1033, 293, 1169, 1066],
 [1543, 2194, 1445, 859, 100, 1803, 2071],
 [1730, 1126, 190, 1242, 230, 1437, 53, 1491],
 [1628, 32, 1984, 142, 1984, 71, 536, 1628, 1903, 205],
 [761, 135, 2141, 1337, 1416, 2155, 679, 509],
 [497, 2207, 2183, 2027],
 [278, 2207, 592, 1748, 374],
 [815, 2202, 2093, 47],
 [1188, 1169, 948, 281, 1198, 2106, 519],
 [1791, 649, 1984, 1381, 1147],
 [1516, 1965, 440, 1662, 2162, 1115, 904],
 [71, 1457, 792, 1276, 965, 269],
 [42, 1761, 1824, 2106],
 [571, 950, 302, 752],
 [2251, 1500, 212, 2207, 21, 2119],
 [155, 252, 419, 588],
 [1231, 487, 2213, 1381, 487, 1369, 970, 829, 388],
 [283, 3, 283],
 [2251, 1181, 436, 402, 485, 974, 2093],
 [2207, 254, 594, 1259, 1984, 1504, 593],
 [2240, 741, 1954, 3, 368, 1379, 530, 1777, 2242, 1758],
 [1022, 1238, 1898, 252, 1791, 2132, 463, 1967],
 [896, 337, 103, 2221, 1984, 1875, 597, 230],
 [1078, 233, 209, 1984, 934, 

In [35]:
padded_sen=pad_sequences(onehot_rep,padding="post",maxlen=30)
padded_sen

array([[ 862, 1374,  100, ...,    0,    0,    0],
       [ 757, 1026,  443, ...,    0,    0,    0],
       [1414, 1048, 1158, ...,    0,    0,    0],
       ...,
       [1414, 1048, 2207, ...,    0,    0,    0],
       [ 762, 2159, 1414, ...,    0,    0,    0],
       [1414, 1048, 1158, ...,    0,    0,    0]])

In [36]:
padded_tag_pos=pad_sequences(tot_ind,padding="post",maxlen=30)
padded_tag_pos

array([[2, 7, 6, ..., 0, 0, 0],
       [5, 5, 4, ..., 0, 0, 0],
       [6, 5, 5, ..., 0, 0, 0],
       ...,
       [6, 5, 4, ..., 0, 0, 0],
       [6, 5, 6, ..., 0, 0, 0],
       [6, 5, 5, ..., 0, 0, 0]])

In [37]:
y = [to_categorical(i, num_classes=len(tags)) for i in padded_tag_pos]
y[0]

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.

In [38]:
X=padded_sen
y=y

In [42]:
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.20)

In [57]:
print(X_tr[0])
print("-----------")
print(X_te[0])

[1543  404 2207 2211 1437 1984 1851 2069 1437  736    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0]
-----------
[1343   27 2093  812    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0]


In [61]:
print(y_tr[0][1])
print("-----------")
print(y_te[0][1])
print("-----------")
print(y[0][1])

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-----------
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-----------
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [43]:
max_len=30
input = Input(shape=(max_len,)) # Input layer
model = Embedding(input_dim=7073, output_dim=30, input_length=max_len)(input) # Word embedding layer
model = Dropout(0.1)(model) # Dropout
model = Bidirectional(LSTM(units=100, return_sequences=True, recurrent_dropout=0.1))(model) # Bi-directional LSTM layer
out = TimeDistributed(Dense(len(tags), activation="softmax"))(model)  # softmax output layer

In [44]:
model = Model(input, out)

In [45]:
model.compile(loss='categorical_crossentropy', optimizer=Adam(lr=1e-5), metrics=['accuracy'])

In [46]:
history = model.fit(np.array(X), np.array(y), batch_size=32, epochs=64, validation_split=0.1, verbose=1)

Epoch 1/64
28/28 [==============================] - 6s 62ms/step - loss: 1.7148 - accuracy: 0.7444 - val_loss: 0.5602 - val_accuracy: 0.8010
Epoch 2/64
28/28 [==============================] - 1s 39ms/step - loss: 0.5041 - accuracy: 0.8587 - val_loss: 0.4497 - val_accuracy: 0.8770
Epoch 3/64
28/28 [==============================] - 1s 41ms/step - loss: 0.4594 - accuracy: 0.8747 - val_loss: 0.4381 - val_accuracy: 0.8713
Epoch 4/64
28/28 [==============================] - 1s 36ms/step - loss: 0.4333 - accuracy: 0.8830 - val_loss: 0.4320 - val_accuracy: 0.8813
Epoch 5/64
28/28 [==============================] - 1s 39ms/step - loss: 0.4090 - accuracy: 0.8881 - val_loss: 0.4234 - val_accuracy: 0.8813
Epoch 6/64
28/28 [==============================] - 1s 43ms/step - loss: 0.3952 - accuracy: 0.8913 - val_loss: 0.4250 - val_accuracy: 0.8810
Epoch 7/64
28/28 [==============================] - 2s 60ms/step - loss: 0.3835 - accuracy: 0.8959 - val_loss: 0.4144 - val_accuracy: 0.8837
Epoch 8/64
28

In [47]:
sample="నా పేరు కృష్ణ"
onehot_rep_input=[one_hot(sample,voc_size)]
input_codded=pad_sequences(onehot_rep_input,padding="post",maxlen=30)
list_input=[]
list_input=model.predict(input_codded)

1/1 [==============================] - 1s 714ms/step


In [48]:
p=list_input
p = np.argmax(p, axis=-1)

In [49]:
ans=[]
for i in range(0,3):
  ans.append(tags2id[p[0][i]])
ans

['PRP', 'NN', 'NN']

In [50]:
print(sample)
print(ans)

నా పేరు కృష్ణ
['PRP', 'NN', 'NN']


In [51]:
import pickle
pickle.dump(model,open('model.pkl','wb'))

In [63]:
y_pre=model.predict(y_te)
# y_pre = np.argmax(y_pre, axis=-1)


ValueError: in user code:

    File "c:\Users\91630\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "c:\Users\91630\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\91630\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "c:\Users\91630\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 2111, in predict_step
        return self(x, training=False)
    File "c:\Users\91630\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\91630\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\input_spec.py", line 219, in assert_input_compatibility
        raise ValueError(

    ValueError: Layer "model" expects 1 input(s), but it received 200 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:2' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:3' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:4' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:5' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:6' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:7' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:8' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:9' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:10' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:11' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:12' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:13' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:14' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:15' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:16' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:17' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:18' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:19' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:20' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:21' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:22' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:23' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:24' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:25' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:26' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:27' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:28' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:29' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:30' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:31' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:32' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:33' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:34' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:35' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:36' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:37' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:38' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:39' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:40' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:41' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:42' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:43' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:44' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:45' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:46' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:47' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:48' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:49' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:50' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:51' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:52' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:53' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:54' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:55' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:56' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:57' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:58' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:59' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:60' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:61' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:62' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:63' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:64' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:65' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:66' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:67' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:68' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:69' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:70' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:71' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:72' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:73' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:74' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:75' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:76' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:77' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:78' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:79' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:80' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:81' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:82' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:83' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:84' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:85' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:86' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:87' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:88' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:89' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:90' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:91' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:92' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:93' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:94' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:95' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:96' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:97' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:98' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:99' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:100' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:101' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:102' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:103' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:104' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:105' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:106' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:107' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:108' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:109' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:110' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:111' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:112' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:113' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:114' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:115' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:116' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:117' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:118' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:119' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:120' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:121' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:122' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:123' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:124' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:125' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:126' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:127' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:128' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:129' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:130' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:131' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:132' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:133' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:134' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:135' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:136' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:137' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:138' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:139' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:140' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:141' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:142' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:143' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:144' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:145' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:146' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:147' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:148' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:149' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:150' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:151' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:152' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:153' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:154' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:155' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:156' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:157' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:158' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:159' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:160' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:161' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:162' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:163' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:164' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:165' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:166' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:167' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:168' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:169' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:170' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:171' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:172' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:173' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:174' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:175' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:176' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:177' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:178' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:179' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:180' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:181' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:182' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:183' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:184' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:185' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:186' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:187' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:188' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:189' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:190' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:191' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:192' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:193' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:194' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:195' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:196' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:197' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:198' shape=(None, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:199' shape=(None, 20) dtype=float32>]
